version: "3"

dotenv: [".env"]
tasks:
  build:
    cmds:
      - task setup
      - task build:linux
      - task build:windows

  setup:
    cmds:
      - rm -rf build/
      - mkdir -p build/linux
      - mkdir -p build/windows

  build:linux:
    dir: build/linux
    cmds:
      - cmake ../.. -DCMAKE_BUILD_TYPE=Release
      - cmake --build . --config Release
      - cpack

  build:windows:
    dir: build/windows
    cmds:
      - cmake ../.. -A Win32
      - cmake --build . --config Release
      - cpack

  release:
    cmds:
      - task: release:linux
      - task: release:windows

  release:linux:
    cmds:
      - mkdir -p ./pkg
      - cmd: mv build/linux/*.tar.gz ./pkg
        ignore_error: true

  release:windows:
    cmds:
      - mkdir -p ./pkg
      - cmd: mv build/linux/*.zip ./pkg
        ignore_error: true
