version: "2"

tasks:
  build:
    cmds:
      - task setup
      - task build:linux
      - task build:windows

  setup:
    cmds:
      - rm -rf build/
      - mkdir -p build/linux
      - mkdir -p build/windows

  build:linux:
    dir: build/linux
    cmds:
      - cmake ../..
      - cmake --build . --config Release
      - cpack

  build:windows:
    dir: build/windows
    cmds:
      - cmake ../.. -A Win32
      - cmake --build . --config Release
      - cpack
